import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
from typing import Dict, List, Tuple
import json

# Add project root to path for imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.model import ModularArithmeticTransformer

def track_weight_norms(results_json_path: str) -> Tuple[List[int], List[float]]:
    """
    Extract weight norm evolution from a results.json file.

    Args:
        results_json_path: Path to the results.json file generated by the training loop.

    Returns:
        Tuple of (steps, weight_norms).
    """
    with open(results_json_path, 'r') as f:
        data = json.load(f)

    steps = []
    norms = []

    if "history" in data:
        for entry in data["history"]:
            steps.append(entry["step"])
            norms.append(entry["weight_norm"])

    return steps, norms

def plot_weight_norm_evolution(condition_paths: Dict[str, str], save_path: str = "results/figures/weight_norms.png"):
    """
    Plot the evolution of weight norms for multiple conditions.

    Args:
        condition_paths: Dictionary mapping condition names to their results.json paths.
        save_path: Path to save the plot.
    """
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    plt.figure(figsize=(10, 6))

    for condition, path in condition_paths.items():
        if os.path.exists(path):
            steps, norms = track_weight_norms(path)
            plt.plot(steps, norms, label=condition)

    plt.xlabel("Training Steps")
    plt.ylabel("L2 Weight Norm")
    plt.title("Weight Norm Evolution During Training")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()

if __name__ == "__main__":
    pass

def visualize_weight_differences(model1: ModularArithmeticTransformer,
                                 model2: ModularArithmeticTransformer,
                                 save_path: str = "results/figures/weight_diff.png",
                                 title: str = "Weight Difference Between Models"):
    """
    Visualize the L2 difference between corresponding weight matrices of two models.
    Useful for comparing a model that grokked vs one that collapsed.

    Args:
        model1: First model (e.g. pure data).
        model2: Second model (e.g. collapsed data).
        save_path: Path to save the visualization.
        title: Title of the plot.
    """
    os.makedirs(os.path.dirname(save_path), exist_ok=True)

    diffs = {}

    # Iterate through parameters and compute L2 norm of the difference
    for (name1, param1), (name2, param2) in zip(model1.named_parameters(), model2.named_parameters()):
        if name1 == name2 and param1.requires_grad:
            diff_norm = torch.norm(param1 - param2).item()
            diffs[name1] = diff_norm

    # Sort for better visualization
    sorted_diffs = {k: v for k, v in sorted(diffs.items(), key=lambda item: item[1], reverse=True)}

    names = list(sorted_diffs.keys())
    values = list(sorted_diffs.values())

    plt.figure(figsize=(12, 8))
    plt.barh(names, values)
    plt.xlabel("L2 Norm of Difference")
    plt.title(title)
    plt.gca().invert_yaxis()  # Highest diffs at the top
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()

def analyze_weight_rank(model: ModularArithmeticTransformer) -> Dict[str, float]:
    """
    Compute the effective rank (entropy of singular values) of key weight matrices.
    This helps detect the low-rank structure that emerges during grokking.

    Args:
        model: Model to analyze.

    Returns:
        Dictionary mapping parameter names to their effective rank.
    """
    ranks = {}

    # 1. Token Embedding
    W_embed = model.token_embed.weight.detach()
    s_embed = torch.linalg.svdvals(W_embed)
    s_embed = s_embed / s_embed.sum()
    entropy_embed = -(s_embed * torch.log(s_embed + 1e-10)).sum()
    ranks['token_embed'] = torch.exp(entropy_embed).item()

    # 2. Output Head
    W_out = model.output_head.weight.detach()
    s_out = torch.linalg.svdvals(W_out)
    s_out = s_out / s_out.sum()
    entropy_out = -(s_out * torch.log(s_out + 1e-10)).sum()
    ranks['output_head'] = torch.exp(entropy_out).item()

    # 3. Attention Projections (if accessible easily, taking the first layer)
    try:
        # Get in_proj_weight of first self-attention layer
        # Shape: (3 * d_model, d_model)
        in_proj = model.transformer.layers[0].self_attn.in_proj_weight.detach()
        d_model = model.d_model

        # Split into Q, K, V
        W_q = in_proj[:d_model, :]
        W_k = in_proj[d_model:2*d_model, :]
        W_v = in_proj[2*d_model:, :]

        for name, matrix in [('attn_q', W_q), ('attn_k', W_k), ('attn_v', W_v)]:
            s = torch.linalg.svdvals(matrix)
            s = s / s.sum()
            entropy = -(s * torch.log(s + 1e-10)).sum()
            ranks[name] = torch.exp(entropy).item()

    except AttributeError:
        # Fallback if architecture is modified and we can't extract in_proj
        pass

    return ranks

def plot_rank_evolution(model_path_template: str,
                        steps: List[int],
                        model_config: dict,
                        save_path: str = "results/figures/rank_evolution.png"):
    """
    Track and plot the effective rank of weight matrices over training steps.

    Args:
        model_path_template: String template for checkpoint path, e.g. 'results/pure/checkpoint_{step}.pt'
        steps: List of training steps to evaluate.
        model_config: Dictionary containing model initialization kwargs.
        save_path: Path to save the plot.
    """
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    device = torch.device("cpu")
    model = ModularArithmeticTransformer(**model_config).to(device)

    history = {}
    valid_steps = []

    for step in steps:
        ckpt_path = model_path_template.format(step=step)
        if not os.path.exists(ckpt_path):
            continue

        checkpoint = torch.load(ckpt_path, map_location=device, weights_only=True)
        model.load_state_dict(checkpoint["model_state"])
        model.eval()

        ranks = analyze_weight_rank(model)
        valid_steps.append(step)

        for k, v in ranks.items():
            if k not in history:
                history[k] = []
            history[k].append(v)

    plt.figure(figsize=(10, 6))
    for k, v in history.items():
        plt.plot(valid_steps, v, label=k)

    plt.xlabel("Training Steps")
    plt.ylabel("Effective Rank")
    plt.title("Evolution of Matrix Ranks During Training")
    plt.legend()
    plt.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()
